services:
  go-main:
    build:
      context: ./auth
      dockerfile: Dockerfile
    
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CLIENT_ID=crXYIYg2cJiNTaw5t-peoPzCRo-3JATNfBd5A86U8t0
      - REDIRECT_URI=com.example.advouch://callback
      - AUTHORIZATION_ENDPOINT=https://esignet.ida.fayda.et/authorize
      - TOKEN_ENDPOINT=https://esignet.ida.fayda.et/v1/esignet/oauth/v2/token
      - USERINFO_ENDPOINT=https://esignet.ida.fayda.et/v1/esignet/oidc/userinfo
      - CLIENT_ASSERTION_TYPE=urn:ietf:params:oauth:client-assertion-type:jwt-bearer  
      - REDIRECT_URL=http://localhost:3000
    networks:
      - auth-network
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - auth-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  redis_data:
    driver: local

networks:
  auth-network:
    driver: bridge
