services:
  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    
    ports:
      - "8080:8080"
    
    env_file:
      - ./auth/.env

    networks:
      - advouch-network
    depends_on:
      redis:
        condition: service_healthy
    

  resource:
    build:
      context: ./resource
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./resource/.env
    
    networks:
      - advouch-network
    
  
  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - advouch-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  redis_data:
    driver: local

networks:
  advouch-network:
    driver: bridge
